"""
Auto-remediation PR mode — opens a GitHub PR with fixed FAQPage/Product JSON-LD + dateModified.
Usage: python scripts/remediation_pr.py --analysis data/output/analysis_X [--apply]
Default is dry-run (prints diff). --apply uses `gh` CLI to open the PR.
Reads site_audit fixes + commerce fix assets; writes *.jsonld.patch files next to the
analysis dir. Never pushes without --apply and never touches prod branches directly.
"""
import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


def build_patches(summary):
    patches = []
    site = summary.get('site_audit', {}) or {}
    for fix in site.get('fixes', [])[:10]:
        patches.append(f'# FIX: {fix}\n# See docs/enterprise.md §4-5 for the publishable asset.\n')
    # FactCheck correction loop: inaccurate brand claims, stats without sources, stale dates
    fc = summary.get('factcheck', {}) or summary.get('verification', {}) or {}
    for p in (fc.get('patches', []) or [])[:20]:
        patches.append(f"# FACTCHECK [{p.get('action', 'fix')}]: {p.get('patch', '')}\n# JSON-LD hint: {p.get('jsonld_hint', '')}\n")
    rate = fc.get('accuracy_intervention_rate')
    if rate is not None:
        patches.append(f"# METRIC: accuracy_intervention_rate={rate} (benchmark inaccurate 7.9%). Applied fixes move this toward 0.\n")
    commerce = summary.get('commerce', {}) or {}
    ucp = commerce.get('ucp', {}) or {}
    if not ucp.get('native_commerce'):
        patches.append('# FIX: publish /api/ucp/mcp search_catalog (ucp.dev) for the native_commerce badge.\n')
    acp = commerce.get('acp', {}) or {}
    if not acp.get('checkout_eligible'):
        patches.append('# FIX: publish /agentic-checkout per agenticcommerce.dev for ACP checkout_eligibility.\n')
    faq = {
        '@context': 'https://schema.org', '@type': 'FAQPage',
        'mainEntity': [{'@type': 'Question', 'name': 'REPLACE_WITH_REAL_QUESTION',
                        'acceptedAnswer': {'@type': 'Answer', 'text': 'REPLACE_WITH_40-60_WORD_DIRECT_ANSWER'}}],
        'dateModified': datetime.now(timezone.utc).date().isoformat(),
        '_note': 'Draft from AEO remediation PR mode — replace placeholders, validate, then merge.',
    }
    patches.append('# ASSET: reports/commerce_fixes/product_offer.jsonld + this FAQPage draft.\n' + json.dumps(faq, indent=2) + '\n')
    return patches


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--analysis', required=True)
    ap.add_argument('--apply', action='store_true')
    ap.add_argument('--apply-factcheck', action='store_true', help='Include FactCheck claim corrections in the PR (identify->correct->republish loop)')
    a = ap.parse_args()
    summary = json.loads((Path(a.analysis) / 'pipeline_summary.json').read_text(encoding='utf-8'))
    patches = build_patches(summary)
    out = Path(a.analysis) / 'remediation.patch'
    out.write_text('\n'.join(patches), encoding='utf-8')
    print(f'Draft remediation ({len(patches)} items) -> {out}')
    if not (a.apply or a.apply_factcheck):
        print('Dry-run. Re-run with --apply (or --apply-factcheck for claim corrections) to open a GitHub PR via `gh`.')
        return
    subprocess.run(['gh', 'pr', 'create', '--title', 'AEO remediation: FAQPage/Product JSON-LD + dateModified',
                    '--body', 'Auto-generated by scripts/remediation_pr.py. Validate JSON-LD before merge.'], check=False)


if __name__ == '__main__':
    main()
